### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by thomasklemm**
This PR updates especially the translations for the standard buttons, the local files and remote files tabs. Also adds in a few texts that can only be seen when hovering on elements.

Some of the phrases didn't sound too natural to a German speaker before :)

### CODE REVIEW

**Comment by bautrukevich** [comment]
@thomasklemm Thank you for your PR!

**Comment by thomasklemm** [comment]
It would be good if you hold back on merging, I'd improve this a bit further, testing it locally w/ this PR branch.

The development instructions seems out of date, since Rails is no longer present in the repo: https://github.com/uploadcare/uploadcare-widget/blob/master/DEVELOPMENT.md. Is there a better way than running `npm run build` after each change in the local file for a complete rebuild?

**Comment by thomasklemm** [comment]
Alright, refined the translations again locally and squashed the commits. Feel free to review again and merge :)

**Comment by jeetiss** [comment]
@thomasklemm thanks for PR ✨

> Is there a better way than running npm run build after each change in the local file for a complete rebuild?

No, I'm working on it #581

**Comment by jeetiss** [comment]
@thomasklemm, everything is okay
I will release this in 3.8.0 with javascript and modules thats is not ready yet.
That's why I don't merge your PR

**Pull request merged**
