### PR TITLE
Additional Translations

### PR DESCRIPTION
**Pull request by gatenbye**
Hi, Eddie from Edudoc Ltd. here. We are building a SaaS product for schools. We are using uploadcare but we need it to be in multiple languages including Azerbaijani. We couldn't find a way to do this with a UPLOADCARE_LOCALE_TRANSLATIONS hash so we are submitting this mutually beneficial pull request.

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
thanks!

also, please take a look at this: https://github.com/uploadcare/social-l10n

**Comment by gatenbye** [comment]
Thanks Dmitry! We will submit a pull request with Azerbaijani translations to that repo shortly. I noticed the CI build failed, is there anything we can do to help?

**Comment by dmitry-mukhin** [comment]
The test itself is broken. Feel free to ignore or take a look at what can be done there :)

**Comment by dmitry-mukhin** [comment]
nvm: #239

**Pull request merged**
