### PR TITLE
Create ca.js.coffee

### PR DESCRIPTION
**Pull request by acmeudg**

### CODE REVIEW

**Comment by acmeudg** [comment]
We have translated uploadcare to Catalan.

**Comment by homm** [comment]
Thanks! Looks good.

**Comment by homm** [comment]
@acmeudg I'm sorry. You've created translation from very outdated version of English localization file. Could you update to current English version: https://github.com/uploadcare/uploadcare-widget/blob/master/app/assets/javascripts/uploadcare/locale/en.js.coffee

It's likely we'll release this as is for today and will update when new version will be ready.

**Comment by homm** [comment]
Another question: do you remember where you found the link to outdated version? I'd like to fix it to prevent future inconveniences.

**Comment by acmeudg** [comment]
We took the spanish translation: https://github.com/uploadcare/uploadcare-widget/blob/master/app/assets/javascripts/uploadcare/locale/es.js.coffee

**Comment by homm** [comment]
Thank you! I've added intro comment for all translation files to prevent such cases in future.

**Pull request merged**
